spring:
  application:
    name: gaming-server-service-admin
  datasource:
    druid:
      url: jdbc:mysql://192.168.75.132:3306/toutiao?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      driver-class-name: com.mysql.jdbc.Driver

dubbo:
  scan:
    base-packages: com.zy.springboot.gamingserverserviceadminapi
  application:
    id: gaming-server-service-admin
    name: gaming-server-service-admin
  protocol:
    id: dubbo
    name: dubbo
    port: 20880
  registry:
    id: zookeeper
    address: zookeeper://192.168.75.132:2181?backup=192.168.75.132:2182,192.168.75.132:2183

mybatis:
    type-aliases-package: com.spring.gamingserverdomain
    mapper-locations: classpath:mapper/*.xml